server:
  port: 8031
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: xcx-client
  cloud:
    nacos:
      discovery:
        server-addr:
        username: nacos
        password: nacos
    loadbalancer:
      cache:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password: root